import test from 'node:test';
import assert from 'node:assert/strict';
import { DatabaseSync } from 'node:sqlite';
import { readFileSync, readdirSync, mkdtempSync, rmSync } from 'node:fs';
import { tmpdir } from 'node:os';
import { join } from 'node:path';
import worker,{handleCommunity,elapsed} from '../worker/index.js';
const now=Date.parse('2026-10-07T20:00:00Z'),stamp=Math.floor((now-10*86400000-23*3600000)/1000),hash='0x'+'a'.repeat(64),blockHash='0x'+'c'.repeat(64),address='0x'+'1'.repeat(40);
class D1 {
  constructor(path=':memory:',migrate=true){this.sqlite=new DatabaseSync(path);if(migrate)for(const f of readdirSync(new URL('../drizzle/',import.meta.url)).filter(f=>f.endsWith('.sql')).sort())this.sqlite.exec(readFileSync(new URL('../drizzle/'+f,import.meta.url),'utf8'));}
  prepare(sql){const db=this.sqlite;let values=[];return{bind(...args){values=args;return this},async first(){return db.prepare(sql).get(...values)||null},async all(){return{results:db.prepare(sql).all(...values)}},async run(){const r=db.prepare(sql).run(...values);return{meta:{changes:Number(r.changes)}}}};}
  async batch(queries){this.sqlite.exec('BEGIN');try{const r=await Promise.all(queries.map(q=>q.all()));this.sqlite.exec('COMMIT');return r}catch(e){this.sqlite.exec('ROLLBACK');throw e;}}
}
function request(method='GET',body,path='/api/community',origin='https://test'){return new Request('https://test'+path,{method,headers:{origin,'content-type':'application/json','cf-connecting-ip':'192.0.2.1'},...(body===undefined?{}:{body:JSON.stringify(body)})});}
function provider({unavailable=false,noRecords=false}={}){return async(url,init)=>{const u=new URL(url),isTest=u.hostname.includes('testnet');if(u.pathname==='/api'){if(unavailable)return Response.json({status:'0',message:'NOTOK',result:'Unavailable'});if(noRecords||isTest)return Response.json({status:'0',message:'No transactions found',result:[]});const a=u.searchParams.get('address');return Response.json({status:'1',result:[{hash,blockNumber:'20',timeStamp:String(stamp),from:a,to:'0x'+'2'.repeat(40),isError:'0'}]});}const body=JSON.parse(init.body);assert(body.every(r=>['eth_chainId','eth_getTransactionReceipt','eth_getBlockByNumber'].includes(r.method)));return Response.json([{id:1,result:'0xab5'},{id:2,result:{transactionHash:hash,blockNumber:'0x14',blockHash,from:address,to:'0x'+'2'.repeat(40),status:'0x1'}},{id:3,result:{number:'0x14',hash:blockHash,timestamp:'0x'+stamp.toString(16),transactions:[hash]}}]);};}
const input={address,message:'I want answers on XP. <script>alert(1)</script>\nMy trust is gone.',topic:'xp',consent:true,days:999999999};
async function add(db,values=input,time=now,p=provider()){const r=await handleCommunity(request('POST',values),{DB:db},p,time);return{status:r.status,body:await r.json()};}
async function list(db,path='/api/community',time=now){const r=await handleCommunity(request('GET',undefined,path),{DB:db},provider(),time);return{status:r.status,body:await r.json()};}
test('empty ledger is real zero; missing storage fails without inventing totals',async()=>{const d=new D1();const a=await list(d);assert.deepEqual(a.body.stats,{wallets:0,days:0,hours:0});assert.deepEqual(a.body.entries,[]);assert.equal((await handleCommunity(request(),{})).status,503);d.sqlite.close();});
test('explicit consent, valid body, bounded messages and same origin are required before verification',async()=>{const d=new D1();let upstream=0;const noFetch=()=>{upstream++;throw Error()};for(const body of [{...input,consent:false},{...input,consent:'true'},{...input,message:'a'.repeat(2501)},{...input,topic:'fake'},{...input,address:'invalid'},{...input,message:'bad\u0000value'}])assert.equal((await handleCommunity(request('POST',body),{DB:d},noFetch,now)).status,400);assert.equal(upstream,0);assert.equal((await handleCommunity(request('POST',input,'/api/community','https://evil'),{DB:d},noFetch,now)).status,403);assert.equal((await handleCommunity(request('POST',{...input,message:'a'.repeat(17000)}),{DB:d},noFetch,now)).status,413);d.sqlite.close();});
test('contribution re-verifies receipt, ignores forged days, counts each wallet once and exposes no private access',async()=>{const d=new D1();const created=await add(d);assert.equal(created.status,201);assert.equal(created.body.days,10);assert.match(created.body.editKey,/^[0-9a-f]{64}$/);assert.equal((await add(d,{...input,address:address.toUpperCase().replace('0X','0x')})).status,409);const a=await list(d);assert.deepEqual(a.body.stats,{wallets:1,days:10,hours:240});assert.equal(a.body.entries[0].message,input.message);assert.equal(a.body.entries[0].transactionUrl,'https://abscan.org/tx/'+hash);assert(!JSON.stringify(a.body).includes('editKey'));assert(!JSON.stringify(a.body).includes('edit_hash'));const row=d.sqlite.prepare('SELECT edit_hash FROM community_contributions').get();assert.notEqual(row.edit_hash,created.body.editKey);d.sqlite.close();});
test('a lost create response can be retried with its private key without double counting',async()=>{const d=new D1(),key='3'.repeat(64);const first=await add(d,{...input,editKey:key}),retry=await add(d,{...input,editKey:key},now+86400000);assert.equal(first.status,201);assert.equal(retry.status,200);assert.equal(retry.body.id,first.body.id);assert.equal(retry.body.editKey,key);assert.equal((await list(d)).body.stats.wallets,1);d.sqlite.close();});
test('concurrent duplicate requests produce one row and one contribution',async()=>{const d=new D1();const r=await Promise.all([add(d),add(d)]);assert.deepEqual(r.map(x=>x.status).sort(),[201,409]);assert.equal((await list(d)).body.stats.wallets,1);d.sqlite.close();});
test('missing verified transaction never enters the total',async()=>{for(const config of [{unavailable:true},{noRecords:true}]){const d=new D1();assert.equal((await add(d,input,now,provider(config))).status,422);assert.equal((await list(d)).body.stats.wallets,0);d.sqlite.close();}});
test('private keys permit edits and removal; address knowledge or a wrong key does not',async()=>{const d=new D1(),a=await add(d),path='/api/community/'+a.body.id;for(const body of [{address},{editKey:'f'.repeat(64)}])assert.equal((await handleCommunity(request('DELETE',body,path),{DB:d},provider(),now)).status,403);assert.equal((await handleCommunity(request('PATCH',{editKey:a.body.editKey,message:'Still waiting for an answer.',topic:'communication'},path),{DB:d},provider(),now+1)).status,200);assert.equal((await list(d)).body.entries[0].message,'Still waiting for an answer.');assert.equal((await list(d)).body.stats.days,10);assert.equal((await handleCommunity(request('DELETE',{editKey:a.body.editKey},path),{DB:d},provider(),now+2)).status,200);assert.equal((await list(d)).body.stats.wallets,0);d.sqlite.close();});
test('records survive a process/database reopen and grow only by whole elapsed days',async()=>{const dir=mkdtempSync(join(tmpdir(),'community-'));try{const path=join(dir,'ledger.sqlite'),d=new D1(path);assert.equal((await add(d)).status,201);d.sqlite.close();const reopened=new D1(path,false);assert.equal((await list(reopened)).body.stats.days,10);assert.equal((await list(reopened,'/api/community',now+3600000)).body.stats.days,11);assert.equal((await list(reopened,'/api/community',now+86400000)).body.stats.days,11);reopened.sqlite.close();}finally{rmSync(dir,{recursive:true,force:true});}});
test('rate limit is persistent across worker instances and blocks repeated verification attempts',async()=>{const d=new D1();for(let i=0;i<5;i++)assert.equal((await add(d,input,now,provider({unavailable:true}))).status,422);assert.equal((await add(d)).status,429);assert.equal((await add(d,input,now+900000)).status,201);d.sqlite.close();});
test('pagination uses stable cursors without duplicating rows or shrinking global totals',async()=>{const d=new D1();const insert=d.sqlite.prepare('INSERT INTO community_contributions (id,address,first_at,tx_hash,network,partial,message,topic,edit_hash,created_at,updated_at) VALUES (?,?,?,?,?,?,?,?,?,?,?)');for(let i=0;i<35;i++)insert.run(crypto.randomUUID(),'0x'+String(i+1).padStart(40,'0'),stamp*1000,hash,'mainnet',0,'Voice '+i,'trust','0'.repeat(64),now+i,now+i);const a=await list(d),b=await list(d,'/api/community?'+new URLSearchParams({cursor:a.body.nextCursor}));assert.equal(a.body.entries.length,30);assert.equal(b.body.entries.length,5);assert.equal(new Set([...a.body.entries,...b.body.entries].map(x=>x.id)).size,35);assert.deepEqual(a.body.stats,b.body.stats);assert.equal(a.body.stats.days,350);assert.equal((await list(d,'/api/community?cursor=bad')).status,400);d.sqlite.close();});
test('home keeps one wallet search before results; community is available on a return page',async()=>{const home=await (await worker.fetch(new Request('https://test/'),{})).text(),page=await (await worker.fetch(new Request('https://test/community'),{})).text();for(const html of [home,page]){new Function(html.match(/<script>([\s\S]*?)<\/script>/)[1]);assert(html.includes('id="community-consent"'));assert(html.includes('Wallet ownership and personal experiences are not verified.'));}assert(home.indexOf('id="receipt-card"')<home.indexOf('id="community"'));assert(!page.includes('<dialog id="theme-gate"'));});
