import test from 'node:test';import assert from 'node:assert/strict';import vm from 'node:vm';import worker from '../worker/index.js';
class Element{constructor(id=''){this.id=id;this.textContent='';this.children=[];this.dataset={};this.events={};this.attributes={};this.hidden=false;this.disabled=false;this.open=false;this.value='';this.checked=false;this.files=[];this.parentElement={open:false};}addEventListener(name,fn){(this.events[name]??=[]).push(fn);}async fire(name,event={}){for(const fn of this.events[name]||[])await fn({preventDefault(){},target:this,...event});}append(...nodes){this.children.push(...nodes);}replaceChildren(...nodes){this.children=nodes;this.textContent='';}setAttribute(k,v){this.attributes[k]=v;}removeAttribute(k){delete this.attributes[k];}focus(){this.focused=true;}select(){this.selected=true;}showModal(){this.open=true;}close(){this.open=false;}querySelectorAll(){return this.choices||[];}querySelector(){return this.children[0]||null;}reset(){}click(){return this.fire('click');}remove(){}set innerHTML(_){throw Error('User messages must be plain text');}}
const address='0x'+'1'.repeat(40),id='12345678-1234-1234-1234-123456789abc',first={network:'mainnet',timestamp:'2025-01-28T22:37:38Z',hash:'0x'+'a'.repeat(64),explorerUrl:'https://abscan.org/tx/0x'+'a'.repeat(64)};
const receipt={schema:'abstract-time-receipt/v1',earliest:first,address,partial:false,generatedAt:'2026-10-07T20:00:00Z',networks:[{network:'mainnet',status:'found',first},{network:'testnet',status:'no-records',first:null,address}]};
function ledger(entries=[]){return{schema:'abstract-community/v1',generatedAt:receipt.generatedAt,stats:{wallets:entries.length,days:entries.length*616,hours:entries.length*14784},entries,nextCursor:null};}
async function client(path='/',override){const html=await(await worker.fetch(new Request('https://test'+path),{})).text(),els={};for(const m of html.matchAll(/<[^>]+\bid="([^"]+)"[^>]*>/g)){const e=els['#'+m[1]]=new Element(m[1]);e.hidden=/\bhidden(?:\s|>)/.test(m[0]);}
const meta=new Element(),dark=new Element();dark.dataset.chooseTheme='dark';const light=new Element();light.dataset.chooseTheme='light';if(els['#theme-gate'])els['#theme-gate'].choices=[dark,light];const writes=[],requests=[],storage=new Map(),entries=[],voices=[],timers=[];
const topicButtons=[...html.matchAll(/<button[^>]*data-follow-topic="([^"]+)"/g)].map(m=>{const e=new Element();e.dataset.followTopic=m[1];return e;});
const questionButtons=[...html.matchAll(/<button[^>]*data-question="([^"]+)"/g)].map(m=>{const e=new Element();e.dataset.question=m[1];e.append(new Element());return e;});
const answerButtons=[...html.matchAll(/<button[^>]*data-follow-answer="([^"]+)"/g)].map(m=>{const e=new Element();e.dataset.followAnswer=m[1];return e;});
const updates=[{id:'xp',publishedAt:'2026-10-07T10:00:00Z',topic:'xp',type:'Official terms',title:'XP terms',body:'A source-backed summary.',url:'https://abs.xyz/terms-of-service'},{id:'legal',publishedAt:'2026-10-07T11:00:00Z',topic:'legal',type:'Community initiative',title:'Legal initiative',body:'The linked organizing statement.',url:'https://x.com/degenlegendmfer/status/2107582275072528598'}];
if(els['#voice-form'])els['#voice-form'].reset=()=>{els['#voice-message'].value='';els['#voice-consent'].checked=false;els['#voice-topic'].value='trust';};
const fetcher=async(url,opts={})=>{requests.push({url,opts});if(opts.method){writes.push(JSON.parse(opts.body));if(override)return override(url,opts,writes,entries);if(url.startsWith('/api/voices')){if(opts.method==='DELETE'){voices.length=0;return Response.json({removed:true});}if(opts.method==='PATCH'){voices[0].message=writes.at(-1).message;voices[0].topic=writes.at(-1).topic;return Response.json({updated:true});}voices.push({id,message:writes.at(-1).message,topic:writes.at(-1).topic,createdAt:receipt.generatedAt});return Response.json({id},{status:201});}if(url==='/api/questions')return Response.json({signals:1});entries.splice(0,entries.length,{id,address,firstAt:first.timestamp,days:616,network:'mainnet',transactionUrl:first.explorerUrl,partial:false,message:writes.at(-1).message,topic:writes.at(-1).topic});return Response.json({id,address,editKey:writes.at(-1).editKey,days:616},{status:201});}if(url.startsWith('/api/updates'))return Response.json({items:updates});if(url.startsWith('/api/voices'))return Response.json({entries:voices});if(url==='/api/questions')return Response.json({questions:questionButtons.map(b=>({id:b.dataset.question,signals:0}))});if(url.startsWith('/api/lookup'))return Response.json(receipt);return Response.json(ledger(entries));};
const context={document:{querySelector:s=>{if(s==='meta[name="theme-color"]')return meta;if(s==='[data-question]')return questionButtons[0];const q=/^\[data-question-count="([^"]+)"\]$/.exec(s);if(q)return questionButtons.find(b=>b.dataset.question===q[1])?.children[0]||null;return els[s]||null;},querySelectorAll:s=>s==='[data-follow-topic]'?topicButtons:s==='[data-question]'?questionButtons:s==='[data-follow-answer]'?answerButtons:[],createElement:()=>new Element(),documentElement:{dataset:{}},body:new Element(),hidden:false},window:{scrollTo(){},open(){}},location:{origin:'https://test',hostname:'test',pathname:path},localStorage:{getItem:k=>storage.get(k)??null,setItem:(k,v)=>storage.set(k,v),removeItem:k=>storage.delete(k)},fetch:fetcher,AbortSignal,URL,URLSearchParams,Blob,crypto,Uint8Array,setTimeout:()=>0,clearTimeout(){},setInterval:fn=>{timers.push(fn);return 0},confirm:()=>true};vm.createContext(context);vm.runInContext(html.match(/<script>([\s\S]*?)<\/script>/)[1],context);await Promise.resolve();if(els['#theme-gate'])await dark.click();return{context,els,writes,requests,storage,timers,entries,voices,topicButtons,questionButtons,answerButtons};}
async function search(c){c.els['#address'].value=address;await c.els['#wallet-form'].fire('submit');await vm.runInContext('loadCommunity()',c.context);await new Promise(resolve=>setImmediate(resolve));}
test('story preparation and private draft saving never publish or tick the consent checkbox',async()=>{
  const c=await client();await search(c);assert.equal(c.els['#receipt-next'].hidden,false);
  await c.els['#tell-story'].click();assert.equal(c.els['#receipt-pack'].open,true);
  c.els['#story-expectation'].value='xp';c.els['#story-text'].value='I want the original reward wording and an answer.';
  await c.els['#story-expectation'].fire('change');assert.equal(c.els['#follow-my-answer'].href,'/answers/xp-purpose');
  await c.els['#save-story-draft'].click();assert.equal(JSON.parse(c.storage.get('aa-story-draft')).text,c.els['#story-text'].value);
  await c.els['#prepare-story'].click();assert.equal(c.writes.length,0);assert.equal(c.els['#voice-consent'].checked,false);
  assert.equal(c.els['#voice-topic'].value,'xp');assert.match(c.els['#voice-message'].value,/I came for XP & rewards/);
  await c.els['#clear-story-draft'].click();assert.equal(c.storage.has('aa-story-draft'),false);assert.equal(c.els['#story-text'].value,'');
});
test('Answer Watch follows stay local and unchecking a follow makes no public write',async()=>{
  const c=await client();const follow=c.answerButtons.find(b=>b.dataset.followAnswer==='shutdown-timeline');
  await follow.click();assert.deepEqual(JSON.parse(c.storage.get('aa-followed-answers')),['shutdown-timeline']);assert.equal(follow.attributes['aria-pressed'],'true');
  await follow.click();assert.deepEqual(JSON.parse(c.storage.get('aa-followed-answers')),[]);assert.equal(c.writes.length,0);
});
test('receipt endpoint toggle updates the visible count without making another lookup or publication',async()=>{
  const c=await client();await search(c);assert.match(c.els['#days-summary'].textContent,/615 calendar days to the wind-down notice/);
  const lookups=c.requests.filter(r=>r.url.startsWith('/api/lookup')).length;
  c.els['#receipt-endpoint'].value='snapshot';await c.els['#receipt-endpoint'].fire('change');
  assert.match(c.els['#days-summary'].textContent,/616 calendar days to your lookup date/);
  assert.equal(c.requests.filter(r=>r.url.startsWith('/api/lookup')).length,lookups);assert.equal(c.writes.length,0);
});
test('a lookup never opts in; explicit posting renders the full vent as text and saves private access',async()=>{const c=await client();await search(c);assert.equal(c.els['#results'].hidden,false);assert.equal(c.writes.length,0);c.els['#community-compose'].open=true;c.els['#community-message'].value='Angry. <img src=x onerror=alert(1)>\nI want answers.';c.els['#community-topic'].value='xp';await c.els['#community-form'].fire('submit');assert.equal(c.writes.length,0);c.els['#community-consent'].checked=true;await c.els['#community-consent'].fire('change');assert.equal(c.els['#community-submit'].disabled,false);await c.els['#community-form'].fire('submit');assert.equal(c.writes.length,1);assert.equal(c.writes[0].consent,true);assert.equal(c.writes[0].address,address);assert.equal(c.writes[0].days,undefined);assert.equal(c.els['#community-total'].textContent,'616');const saved=JSON.parse(c.storage.get('abstract-community-access'));assert.equal(saved[address].id,id);assert.match(saved[address].editKey,/^[0-9a-f]{64}$/);const voice=c.els['#community-rows'].children[0].children[3];assert.equal(voice.children[1].textContent,c.writes[0].message);assert.equal(c.els['#community-compose'].open,false);});
test('a network failure keeps the vent and pending private key available for a safe retry',async()=>{const c=await client('/',()=>{throw Error('Connection lost');});await search(c);c.els['#community-compose'].open=true;c.els['#community-message'].value='Months of time and no answers.';c.els['#community-topic'].value='trust';c.els['#community-consent'].checked=true;await c.els['#community-form'].fire('submit');assert.equal(c.els['#community-message'].value,'Months of time and no answers.');assert.equal(c.els['#community-compose'].open,true);assert.match(c.els['#community-status'].textContent,/Connection lost/);await c.els['#community-form'].fire('submit');assert.equal(c.writes.length,2);assert.equal(c.writes[0].editKey,c.writes[1].editKey);assert.equal(c.els['#community-submit'].disabled,false);});
test('the community return page loads shared totals without requiring another wallet lookup',async()=>{const c=await client('/community');await new Promise(resolve=>setImmediate(resolve));assert.equal(c.writes.length,0);assert.equal(c.requests[0].url,'/api/community');assert.equal(c.els['#community-total'].textContent,'0');assert.equal(c.els['#community-empty'].hidden,false);assert.equal(c.els['#community-search-link'].hidden,false);});

test('wallet-free voices require consent, render arbitrary vent text safely, and retain private edit access',async()=>{const c=await client('/community');await new Promise(resolve=>setImmediate(resolve));const message='I want answers. <img src=x onerror=alert(1)>\nThis is my experience.';c.els['#voice-message'].value=message;c.els['#voice-topic'].value='trust';await c.els['#voice-form'].fire('submit');assert.equal(c.writes.length,0);c.els['#voice-consent'].checked=true;await c.els['#voice-form'].fire('submit');assert.equal(c.writes.length,1);assert.equal(c.writes[0].address,undefined);assert.equal(c.writes[0].days,undefined);assert.equal(c.els['#community-total'].textContent,'0');assert.equal(c.els['#voice-wall-posts'].children[0].children[1].textContent,message);const access=JSON.parse(c.storage.get('aa-voice-access'));assert.match(access[id].editKey,/^[0-9a-f]{64}$/);assert.equal(c.storage.has('aa-voice-draft-key'),false);assert.equal(c.els['#voice-message'].value,'');const edit=c.els['#voice-wall-posts'].children[0].children[2].children[0];await edit.click();assert.equal(c.els['#voice-message'].value,message);assert.equal(c.els['#voice-consent'].checked,false);c.els['#voice-message'].value='I have updated my account and still want answers.';c.els['#voice-consent'].checked=true;await c.els['#voice-form'].fire('submit');assert.equal(c.writes[1].editKey,access[id].editKey);assert.equal(c.els['#voice-wall-posts'].children[0].children[1].textContent,c.writes[1].message);const remove=c.els['#voice-wall-posts'].children[0].children[2].children[1];await remove.click();assert.equal(c.els['#voice-wall-posts'].children.length,0);assert.deepEqual(JSON.parse(c.storage.get('aa-voice-access')),{});});
test('a failed voice submission keeps the text and the same private draft key for a retry',async()=>{const c=await client('/community',()=>{throw Error('Connection lost');});c.els['#voice-message'].value='I still need to be heard after this announcement.';c.els['#voice-topic'].value='trust';c.els['#voice-consent'].checked=true;await c.els['#voice-form'].fire('submit');await c.els['#voice-form'].fire('submit');assert.equal(c.writes.length,2);assert.equal(c.writes[0].editKey,c.writes[1].editKey);assert.equal(c.els['#voice-message'].value,c.writes[0].message);assert.equal(c.els['#voice-submit'].disabled,false);assert.match(c.els['#voice-status'].textContent,/Connection lost/);});
test('followed topics filter updates, marking read clears new badges, and question backing is explicit and idempotent',async()=>{const c=await client();await new Promise(resolve=>setImmediate(resolve));assert.equal(c.els['#update-feed'].children.length,2);assert.equal(c.els['#updates-new-count'].textContent,'2 new in your topics');const xp=c.topicButtons.find(b=>b.dataset.followTopic==='xp');await xp.click();assert.equal(c.els['#update-feed'].children.length,1);assert.deepEqual(JSON.parse(c.storage.get('aa-followed-topics')),['xp']);await c.els['#updates-mark-read'].click();assert.equal(c.els['#updates-new-count'].textContent,'You’re up to date');assert.equal(c.writes.length,0);await c.questionButtons[0].click();await c.questionButtons[0].click();assert.equal(c.writes.length,1);assert.equal(c.writes[0].questionId,'shutdown-timeline');assert.equal(c.questionButtons[0].children[0].textContent,'1');assert.equal(c.questionButtons[0].attributes['aria-pressed'],'true');});
